name: Tests

on:
  push:
    branches:
      - master
      - add/ga-tests-old
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0']

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, openssl, gmp
          coverage: none

      - name: Remove pre-installed chrome
        run: |
          sudo apt remove google-chrome-stable

      - name: Setup Chrome 74
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: 637110

      - name: Setup chromedriver
        run: |
          wget https://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip
          CHROMEDRIVER_DIR="/usr/local/share/chrome_driver"
          CHROMEDRIVER_BIN="$CHROMEDRIVER_DIR/chromedriver"
          sudo unzip -oqq chromedriver_linux64.zip -d $CHROMEDRIVER_DIR
          sudo chmod +x $CHROMEDRIVER_BIN
          CHROMIUM_BIN=$(which chrome)
          sudo rm /usr/bin/chromium
          sudo rm /usr/bin/chromium-browser
          sudo ln -s $CHROMIUM_BIN /usr/bin/chromium
          sudo ln -s $CHROMIUM_BIN /usr/bin/chromium-browser

      - run: |
          echo "DISPLAY=:99" >> $GITHUB_ENV
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Prepare composer
        run: |
          EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

          if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
          then
              >&2 echo 'ERROR: Invalid installer checksum'
              rm composer-setup.php
              exit 1
          fi

          sudo php composer-setup.php --quiet --install-dir=/usr/local/bin --filename=composer
          RESULT=$?
          rm composer-setup.php
          composer config discard-changes true
          composer install

      - name: Setup web-push-testing-service
        run: |
          npm install web-push-testing-service -g

      - name: Run tests
        run: |
          web-push-testing-service start example -p 9012
          composer test:unit
          web-push-testing-service stop example
          composer test:typing
          composer test:syntax
